name: Deploy ke AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy ke Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 18.141.231.95
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/uas-project
            git pull origin main
            docker compose up -d --build
