with:
          host: 18.141.231.95
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Tambahkan baris di bawah ini untuk melewati verifikasi host
          proxy_timeout: 60s
          command_timeout: 2m
          fingerprint: "" 
          # Atau tambahkan opsi ini agar tidak menolak koneksi:
          envs: SSH_OPTIONS
          script_stop: true
          script: |
            mkdir -p ~/uas-project
            cd ~/uas-project
            git pull origin main || git clone https://github.com/mohamadkhadik2-crypto/administrasi-server-B-mohamad-kadik.git .
            docker compose up -d --build
